name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /opt/apps/laravel-pos/app

            git pull origin main

            docker compose up -d --build

            docker exec laravel-pos-app php artisan migrate --force
            docker exec laravel-pos-app php artisan optimize:clear
            docker exec laravel-pos-app php artisan optimize
