name: Deploy Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_VPS_HOST }}
          username: ${{ secrets.DEV_VPS_USER }}
          key: ${{ secrets.DEV_VPS_SSH_KEY }}
          port: ${{ secrets.DEV_VPS_PORT }}
          script: |
            cd /opt/apps/laravel-pos/app

            git fetch origin
            git checkout development
            git reset --hard origin/development

            docker compose up -d --build

            docker exec laravel-pos-app php artisan migrate --force
            docker exec laravel-pos-app php artisan optimize:clear
            docker exec laravel-pos-app php artisan optimize
